version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db:/docker-encrypoint-initdb.d/

  web:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - static_volume:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: