version: '3'

services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db  
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db:/docker-encrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/


  pre_web:
    build: 
      context: .
      dockerfile: dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py collectstatic --noinput
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    env_file:
      - ./.env

  web:
    build:
      context: .
    restart: always
    command: gunicorn place_remeber.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - pre_web

  nginx:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - static_volume:/var/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/ssl/certs/cert.pem
      - ./ssl/key.pem:/etc/ssl/certs/key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: